# Generated by Django 2.0.7 on 2019-11-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='显示顺序')),
                ('image', models.ImageField(blank=True, upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'luffy_banner',
            },
        ),
    ]
