# Generated by Django 2.0.7 on 2019-11-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上线')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=32, verbose_name='图片名')),
                ('order', models.IntegerField(verbose_name='显示顺序')),
                ('image', models.ImageField(blank=True, upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('link', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'luffy_banner',
            },
        ),
    ]
